export class ImportFieldValues {

  static docTypeMapping = [
    //  {label:'Select Document Type', value:null,key:" IN - Brownfields ,  IN - ELTF ,  IN - LUST , IN - State Cleanup,IN - UST, IN - VRP "},
    { label: '329 IAC 9-3-1 Records Request', value: '329 IAC 9-3-1 Records Request', key: " IN - UST" },
    { label: 'COFA Approved', value: 'COFA Approved', key: " IN - UST" },
    { label: 'Community Relations', value: 'Community Relations',  key: "IN - Brownfields, IN - State Cleanup, IN - VRP "  },
    { label: 'Corrective Action', value: 'Corrective Action', key: " IN - UST,IN - Brownfields, IN - ELTF, IN - LUST, IN - State Cleanup  " },
    { label: 'Correspondence', value: 'Correspondence', key: " IN - UST,IN - Brownfields, IN - ELTF, IN - LUST , IN - State Cleanup , IN - VRP " },
    { label: 'Cost Recovery', value: 'Cost Recovery', key: "IN - Brownfields, IN - State Cleanup , IN - VRP" },
    { label: 'ELTF Claim', value: 'ELTF Claim', key: " IN - ELTF" },
    { label: 'Email Correspondence', value: 'Email Correspondence', key: " IN - UST" },
    { label: 'Emergency Response', value: 'Emergency Response', key: "IN - Brownfields, IN - LUST, IN - State Cleanup  " },
    { label: 'Enforcement', value: 'Enforcement', key: " IN - UST,IN - Brownfields, IN - LUST , IN - State Cleanup , IN - VRP" },
    { label: 'Financial Responsibility', value: 'Financial Responsibility', key: " IN - UST," },
    { label: 'Inspection', value: 'Inspection', key: " IN - UST, IN - State Cleanup " },
    { label: 'Institutional Control', value: 'Institutional Control', key: "IN - Brownfields, IN - LUST, IN - State Cleanup , IN - VRP " },
    { label: 'LUST', value: 'LUST', key: "LUST" },
    { label: 'Notification Form', value: 'Notification Form', key: " IN - UST" },
    { label: 'Notification Form Denied', value: 'Notification Form Denied', key: " IN - UST" },
    { label: 'Other', value: 'Other', key: " IN - UST, IN - State Cleanup " },
    { label: 'Quarterly Monitoring', value: 'Quarterly Monitoring', key: "IN - Brownfields, IN - LUST, IN - State Cleanup , IN - VRP " },
    { label: 'Remediation', value: 'Remediation', key: "IN - VRP" },
    { label: 'Return to Compliance', value: 'Return to Compliance', key: " IN - UST," },
    { label: 'Screening/Assessment', value: 'Screening/Assessment', key: "IN - Brownfields, IN - LUST , IN - State Cleanup , IN - VRP " },
    { label: 'Site Characterization - FSI', value: 'Site Characterization - FSI', key: "IN - Brownfields, IN - LUST, IN - State Cleanup  " },
    { label: 'Site Characterization – FSI', value: 'Site Characterization – FSI', key: "IN - VRP" },
    { label: 'Site Characterization - ISC', value: 'Site Characterization - ISC', key: "IN - Brownfields, IN - LUST , IN - State Cleanup " },
    { label: 'Site Characterization – ISI', value: 'Site Characterization – ISI', key: "IN - VRP" },
    { label: 'Site Characterization - LSI', value: 'Site Characterization - LSI', key: "IN - Brownfields, IN - LUST, IN - State Cleanup , IN - VRP " },
    { label: 'Site Closure', value: 'Site Closure', key: 'IN - Brownfields, IN - LUST, IN - State Cleanup , IN - VRP ' },
    { label: 'Site Decision', value: 'Site Decision', key: "IN - State Cleanup " },
    { label: 'Technical Review', value: 'Technical Review', key: "IN - Brownfields, IN - State Cleanup " },
    { label: 'UST Closure', value: 'UST Closure', key: " IN - LUST , IN - State Cleanup " },
    { label: 'UST Closure Report', value: 'UST Closure Report', key: " IN - UST, IN - LUST " },
    { label: 'UST Removal Approval', value: 'UST Removal Approval', key: " IN - UST," },
    { label: 'UST Removal Request', value: 'UST Removal Request', key: " IN - UST," },
    { label: 'Violation', value: 'Violation', key: " IN - UST,IN - Brownfields, IN - LUST , IN - State Cleanup " },
    { label: 'VRP Application', value: 'VRP Application', key: "IN - VRP" },
  ];

  static scopeOfWorkMapping = [
    { label: 'ATG Functionality', value: 'ATG Functionality', key: " IN - UST " },
    { label: 'Cathodic Protection (Impressed) Test', value: 'Cathodic Protection (Impressed) Test', key: " IN - UST " },
    { label: 'Cathodic Protection (Sacrificial) Test', value: 'Cathodic Protection (Sacrificial) Test', key: " IN - UST " },
    { label: 'Compliance Management', value: 'Compliance Management', key: " IN - UST " },
    { label: 'Drum Disposal', value: 'Drum Disposal', key: " IN - UST " },
    { label: 'E-Stop and Interstitial Sensor Tests', value: 'E-Stop and Interstitial Sensor Tests', key: " IN - UST " },
    { label: 'Helium Leak Testing', value: 'Helium Leak Testing', key: " IN - UST " },
    { label: 'Impact Valve', value: 'Impact Valve', key: " IN - UST " },
    { label: 'Internal Tank Lining Inspection', value: 'Internal Tank Lining Inspection', key: " IN - UST " },
    { label: 'Interstitial Tank Pressure Testing', value: 'Interstitial Tank Pressure Testing', key: " IN - UST " },
    { label: 'Line Tightness Testing', value: 'Line Tightness Testing', key: " IN - UST " },
    { label: 'Notification Form', value: 'Notification Form', key: " IN - UST " },
    { label: 'Operator Training', value: 'Operator Training', key: " IN - UST " },
    { label: 'State Cleanup', value: 'State Cleanup', key: " IN - UST " },
    { label: 'Sump Sensor', value: 'Sump Sensor', key: " IN - UST " },
    { label: 'Tank Closure', value: 'Tank Closure', key: " IN - UST " },
    { label: 'Tank Tightness Testing', value: 'Tank Tightness Testing', key: " IN - UST " },
    { label: 'Voluntary Remediation Program (VRP)', value: 'Voluntary Remediation Program (VRP)', key: " IN - UST " },
    { label: 'Active', value: 'Active', key: " IN - LUST ,  IN - State Cleanup ,  IN - VRP  " },
    { label: 'Compliant', value: 'Compliant', key: " IN - LUST ,  IN - State Cleanup ,  IN - VRP  " },
    { label: 'Deactivated (No Release)', value: 'Deactivated (No Release)', key: " IN - LUST ,  IN - State Cleanup ,  IN - VRP  " },
    { label: 'Discontinued (Active)', value: 'Discontinued (Active)', key: " IN - LUST ,  IN - State Cleanup ,  IN - VRP  " },
    { label: 'NFA', value: 'NFA', key: " IN - LUST ,  IN - State Cleanup ,  IN - VRP  " },
    { label: 'No Paper File (Active)', value: 'No Paper File (Active)', key: " IN - LUST ,  IN - State Cleanup ,  IN - VRP  " },
    { label: 'Reffered to Another IDEM Program', value: 'Reffered to Another IDEM Program', key: " IN - LUST ,  IN - State Cleanup ,  IN - VRP  " },

  ]

  static stateProgramMapping = [
    // {label:'Select State Program', value:null},
    { label: 'IN - Brownfields', value: 'IN-Brownfields' , enable: true},
    { label: 'IN - ELTF', value: 'IN - ELTF', enable: true },
    { label: 'IN - LUST', value: 'IN - LUST', enable: true },
    { label: 'IN - State Cleanup', value: 'IN - State Cleanup' , enable: true },
    { label: 'IN - UST', value: 'IN - UST', enable: true },
    { label: 'IN - VRP', value: 'IN - VRP', enable: true },
  ]

  static stateProgramMappingForDocumentType = [
    // {label:'Select State Program', value:null},
    {
      label: 'IN - Brownfields', properties: 
        [
          { label: '329 IAC 9-3-1 Records Request', value: '329 IAC 9-3-1 Records Request', enable: false },
          { label: 'COFA Approved', value: 'COFA Approved', enable: false },
          { label: 'Community Relations', value: 'Community Relations', enable: true },
          { label: 'Corrective Action', value: 'Corrective Action', enable: true },
          { label: 'Correspondence', value: 'Correspondence', enable: true },
          { label: 'Cost Recovery', value: 'Cost Recovery', enable: true },
          { label: 'ELTF Claim', value: 'ELTF Claim', enable: false },
          { label: 'Email Correspondence', value: 'Email Correspondence', enable: false },
          { label: 'Emergency Response', value: 'Emergency Response', enable: true },
          { label: 'Enforcement', value: 'Enforcement', enable: true },
          { label: 'Financial Responsibility', value: 'Financial Responsibility', enable: false },
          { label: 'Inspection', value: 'Inspection', enable: false },
          { label: 'Institutional Control', value: 'Institutional Control', enable: true },
          { label: 'LUST', value: 'LUST', enable: false },
          { label: 'Notification Form', value: 'Notification Form', enable: false },
          { label: 'Notification Form Denied', value: 'Notification Form Denied', enable: false },
          { label: 'Other', value: 'Other', enable: false },
          { label: 'Quarterly Monitoring', value: 'Quarterly Monitoring', enable: true },
          { label: 'Remediation', value: 'Remediation', enable: false },
          { label: 'Return to Compliance', value: 'Return to Compliance', enable: false },
          { label: 'Screening/Assessment', value: 'Screening/Assessment', enable: true },
          { label: 'Site Characterization - FSI', value: 'Site Characterization - FSI', enable: true },
          { label: 'Site Characterization – FSI', value: 'Site Characterization – FSI', enable: false },
          { label: 'Site Characterization - ISC', value: 'Site Characterization - ISC', enable: true },
          { label: 'Site Characterization – ISI', value: 'Site Characterization – ISI', enable: false },
          { label: 'Site Characterization - LSI', value: 'Site Characterization - LSI', enable: true },
          { label: 'Site Closure', value: 'Site Closure', enable: true },
          { label: 'Site Decision', value: 'Site Decision', enable: false },
          { label: 'Technical Review', value: 'Technical Review', enable: true },
          { label: 'UST Closure', value: 'UST Closure', enable: false },
          { label: 'UST Closure Report', value: 'UST Closure Report', enable: false },
          { label: 'UST Removal Approval', value: 'UST Removal Approval', enable: false },
          { label: 'UST Removal Request', value: 'UST Removal Request', enable: false },
          { label: 'Violation', value: 'Violation', enable: true },
          { label: 'VRP Application', value: 'VRP Application', enable: false }
      ]
    },
    {
      label: 'IN - ELTF', properties: 
        [
          { label: '329 IAC 9-3-1 Records Request', value: '329 IAC 9-3-1 Records Request', enable: false },
          { label: 'COFA Approved', value: 'COFA Approved', enable: false },
          { label: 'Community Relations', value: 'Community Relations', enable: false },
          { label: 'Corrective Action', value: 'Corrective Action', enable: true },
          { label: 'Correspondence', value: 'Correspondence', enable: true },
          { label: 'Cost Recovery', value: 'Cost Recovery', enable: false },
          { label: 'ELTF Claim', value: 'ELTF Claim', enable: true },
          { label: 'Email Correspondence', value: 'Email Correspondence', enable: false },
          { label: 'Emergency Response', value: 'Emergency Response', enable: false },
          { label: 'Enforcement', value: 'Enforcement', enable: false },
          { label: 'Financial Responsibility', value: 'Financial Responsibility', enable: false },
          { label: 'Inspection', value: 'Inspection', enable: false },
          { label: 'Institutional Control', value: 'Institutional Control', enable: false },
          { label: 'LUST', value: 'LUST', enable: false },
          { label: 'Notification Form', value: 'Notification Form', enable: false },
          { label: 'Notification Form Denied', value: 'Notification Form Denied', enable: false },
          { label: 'Other', value: 'Other', enable: false },
          { label: 'Quarterly Monitoring', value: 'Quarterly Monitoring', enable: false },
          { label: 'Remediation', value: 'Remediation', enable: false },
          { label: 'Return to Compliance', value: 'Return to Compliance', enable: false },
          { label: 'Screening/Assessment', value: 'Screening/Assessment', enable: false },
          { label: 'Site Characterization - FSI', value: 'Site Characterization - FSI', enable: false },
          { label: 'Site Characterization – FSI', value: 'Site Characterization – FSI', enable: false },
          { label: 'Site Characterization - ISC', value: 'Site Characterization - ISC', enable: false },
          { label: 'Site Characterization – ISI', value: 'Site Characterization – ISI', enable: false },
          { label: 'Site Characterization - LSI', value: 'Site Characterization - LSI', enable: false },
          { label: 'Site Closure', value: 'Site Closure', enable: false },
          { label: 'Site Decision', value: 'Site Decision', enable: false },
          { label: 'Technical Review', value: 'Technical Review', enable: false },
          { label: 'UST Closure', value: 'UST Closure', enable: false },
          { label: 'UST Closure Report', value: 'UST Closure Report', enable: false },
          { label: 'UST Removal Approval', value: 'UST Removal Approval', enable: false },
          { label: 'UST Removal Request', value: 'UST Removal Request', enable: false },
          { label: 'Violation', value: 'Violation', enable: false },
          { label: 'VRP Application', value: 'VRP Application', enable: false }
      ]
    },
    {
      label: 'IN - LUST', properties: 
        [
          { label: '329 IAC 9-3-1 Records Request', value: '329 IAC 9-3-1 Records Request', enable: false },
          { label: 'COFA Approved', value: 'COFA Approved', enable: false },
          { label: 'Community Relations', value: 'Community Relations', enable: false },
          { label: 'Corrective Action', value: 'Corrective Action', enable: true },
          { label: 'Correspondence', value: 'Correspondence', enable: true },
          { label: 'Cost Recovery', value: 'Cost Recovery', enable: false },
          { label: 'ELTF Claim', value: 'ELTF Claim', enable: false },
          { label: 'Email Correspondence', value: 'Email Correspondence', enable: false },
          { label: 'Emergency Response', value: 'Emergency Response', enable: true },
          { label: 'Enforcement', value: 'Enforcement', enable: true },
          { label: 'Financial Responsibility', value: 'Financial Responsibility', enable: false },
          { label: 'Inspection', value: 'Inspection', enable: false },
          { label: 'Institutional Control', value: 'Institutional Control', enable: true },
          { label: 'LUST', value: 'LUST', enable: false },
          { label: 'Notification Form', value: 'Notification Form', enable: false },
          { label: 'Notification Form Denied', value: 'Notification Form Denied', enable: false },
          { label: 'Other', value: 'Other', enable: false },
          { label: 'Quarterly Monitoring', value: 'Quarterly Monitoring', enable: true },
          { label: 'Remediation', value: 'Remediation', enable: false },
          { label: 'Return to Compliance', value: 'Return to Compliance', enable: false },
          { label: 'Screening/Assessment', value: 'Screening/Assessment', enable: true },
          { label: 'Site Characterization - FSI', value: 'Site Characterization - FSI', enable: true },
          { label: 'Site Characterization – FSI', value: 'Site Characterization – FSI', enable: false },
          { label: 'Site Characterization - ISC', value: 'Site Characterization - ISC', enable: true },
          { label: 'Site Characterization – ISI', value: 'Site Characterization – ISI', enable: false },
          { label: 'Site Characterization - LSI', value: 'Site Characterization - LSI', enable: true },
          { label: 'Site Closure', value: 'Site Closure', enable: true },
          { label: 'Site Decision', value: 'Site Decision', enable: false },
          { label: 'Technical Review', value: 'Technical Review', enable: false },
          { label: 'UST Closure', value: 'UST Closure', enable: true },
          { label: 'UST Closure Report', value: 'UST Closure Report', enable: true },
          { label: 'UST Removal Approval', value: 'UST Removal Approval', enable: false },
          { label: 'UST Removal Request', value: 'UST Removal Request', enable: false },
          { label: 'Violation', value: 'Violation', enable: true },
          { label: 'VRP Application', value: 'VRP Application', enable: false }
      ]
    },
    {
      label: 'IN - State Cleanup', properties: 
        [
          { label: '329 IAC 9-3-1 Records Request', value: '329 IAC 9-3-1 Records Request', enable: false },
          { label: 'COFA Approved', value: 'COFA Approved', enable: false },
          { label: 'Community Relations', value: 'Community Relations', enable: true },
          { label: 'Corrective Action', value: 'Corrective Action', enable: true },
          { label: 'Correspondence', value: 'Correspondence', enable: true },
          { label: 'Cost Recovery', value: 'Cost Recovery', enable: true },
          { label: 'ELTF Claim', value: 'ELTF Claim', enable: false },
          { label: 'Email Correspondence', value: 'Email Correspondence', enable: false },
          { label: 'Emergency Response', value: 'Emergency Response', enable: true },
          { label: 'Enforcement', value: 'Enforcement', enable: true },
          { label: 'Financial Responsibility', value: 'Financial Responsibility', enable: false },
          { label: 'Inspection', value: 'Inspection', enable: true },
          { label: 'Institutional Control', value: 'Institutional Control', enable: true },
          { label: 'LUST', value: 'LUST', enable: false },
          { label: 'Notification Form', value: 'Notification Form', enable: false },
          { label: 'Notification Form Denied', value: 'Notification Form Denied', enable: false },
          { label: 'Other', value: 'Other', enable: true },
          { label: 'Quarterly Monitoring', value: 'Quarterly Monitoring', enable: true },
          { label: 'Remediation', value: 'Remediation', enable: false },
          { label: 'Return to Compliance', value: 'Return to Compliance', enable: false },
          { label: 'Screening/Assessment', value: 'Screening/Assessment', enable: true },
          { label: 'Site Characterization - FSI', value: 'Site Characterization - FSI', enable: true },
          { label: 'Site Characterization – FSI', value: 'Site Characterization – FSI', enable: false },
          { label: 'Site Characterization - ISC', value: 'Site Characterization - ISC', enable: true },
          { label: 'Site Characterization – ISI', value: 'Site Characterization – ISI', enable: false },
          { label: 'Site Characterization - LSI', value: 'Site Characterization - LSI', enable: true },
          { label: 'Site Closure', value: 'Site Closure', enable: true },
          { label: 'Site Decision', value: 'Site Decision', enable: true },
          { label: 'Technical Review', value: 'Technical Review', enable: true },
          { label: 'UST Closure', value: 'UST Closure', enable: true },
          { label: 'UST Closure Report', value: 'UST Closure Report', enable: false },
          { label: 'UST Removal Approval', value: 'UST Removal Approval', enable: false },
          { label: 'UST Removal Request', value: 'UST Removal Request', enable: false },
          { label: 'Violation', value: 'Violation', enable: true },
          { label: 'VRP Application', value: 'VRP Application', enable: false }
      ]
    },
    {
      label: 'IN - UST', properties: 
        [
          { label: '329 IAC 9-3-1 Records Request', value: '329 IAC 9-3-1 Records Request', enable: true },
          { label: 'COFA Approved', value: 'COFA Approved', enable: true   },
          { label: 'Community Relations', value: 'Community Relations', enable: false },
          { label: 'Corrective Action', value: 'Corrective Action', enable: true },
          { label: 'Correspondence', value: 'Correspondence', enable: true },
          { label: 'Cost Recovery', value: 'Cost Recovery', enable: false },
          { label: 'ELTF Claim', value: 'ELTF Claim', enable: false },
          { label: 'Email Correspondence', value: 'Email Correspondence', enable: true },
          { label: 'Emergency Response', value: 'Emergency Response', enable: false },
          { label: 'Enforcement', value: 'Enforcement', enable: true },
          { label: 'Financial Responsibility', value: 'Financial Responsibility', enable: true },
          { label: 'Inspection', value: 'Inspection', enable: true },
          { label: 'Institutional Control', value: 'Institutional Control', enable: false },
          { label: 'LUST', value: 'LUST', enable: false },
          { label: 'Notification Form', value: 'Notification Form', enable: true },
          { label: 'Notification Form Denied', value: 'Notification Form Denied', enable: true },
          { label: 'Other', value: 'Other', enable: true },
          { label: 'Quarterly Monitoring', value: 'Quarterly Monitoring', enable: false },
          { label: 'Remediation', value: 'Remediation', enable: false },
          { label: 'Return to Compliance', value: 'Return to Compliance', enable: true },
          { label: 'Screening/Assessment', value: 'Screening/Assessment', enable: false },
          { label: 'Site Characterization - FSI', value: 'Site Characterization - FSI', enable: false },
          { label: 'Site Characterization – FSI', value: 'Site Characterization – FSI', enable: false },
          { label: 'Site Characterization - ISC', value: 'Site Characterization - ISC', enable: false },
          { label: 'Site Characterization – ISI', value: 'Site Characterization – ISI', enable: false },
          { label: 'Site Characterization - LSI', value: 'Site Characterization - LSI', enable: false },
          { label: 'Site Closure', value: 'Site Closure', enable: false },
          { label: 'Site Decision', value: 'Site Decision', enable: false },
          { label: 'Technical Review', value: 'Technical Review', enable: false },
          { label: 'UST Closure', value: 'UST Closure', enable: true },
          { label: 'UST Closure Report', value: 'UST Closure Report', enable: true },
          { label: 'UST Removal Approval', value: 'UST Removal Approval', enable: true },
          { label: 'UST Removal Request', value: 'UST Removal Request', enable: true },
          { label: 'Violation', value: 'Violation', enable: true },
          { label: 'VRP Application', value: 'VRP Application', enable: false }
      ]
    },
    {
      label: 'IN - VRP', properties: 
        [
          { label: '329 IAC 9-3-1 Records Request', value: '329 IAC 9-3-1 Records Request', enable: false },
          { label: 'COFA Approved', value: 'COFA Approved', enable: false  },
          { label: 'Community Relations', value: 'Community Relations', enable: true },
          { label: 'Corrective Action', value: 'Corrective Action', enable: false },
          { label: 'Correspondence', value: 'Correspondence', enable: true },
          { label: 'Cost Recovery', value: 'Cost Recovery', enable: true },
          { label: 'ELTF Claim', value: 'ELTF Claim', enable: false },
          { label: 'Email Correspondence', value: 'Email Correspondence', enable: false },
          { label: 'Emergency Response', value: 'Emergency Response', enable: false },
          { label: 'Enforcement', value: 'Enforcement', enable: true },
          { label: 'Financial Responsibility', value: 'Financial Responsibility', enable: false },
          { label: 'Inspection', value: 'Inspection', enable: false },
          { label: 'Institutional Control', value: 'Institutional Control', enable: false },
          { label: 'LUST', value: 'LUST', enable: false },
          { label: 'Notification Form', value: 'Notification Form', enable: false },
          { label: 'Notification Form Denied', value: 'Notification Form Denied', enable: false },
          { label: 'Other', value: 'Other', enable: false },
          { label: 'Quarterly Monitoring', value: 'Quarterly Monitoring', enable: true },
          { label: 'Remediation', value: 'Remediation', enable: true },
          { label: 'Return to Compliance', value: 'Return to Compliance', enable: false },
          { label: 'Screening/Assessment', value: 'Screening/Assessment', enable: true },
          { label: 'Site Characterization - FSI', value: 'Site Characterization - FSI', enable: false },
          { label: 'Site Characterization – FSI', value: 'Site Characterization – FSI', enable: true },
          { label: 'Site Characterization - ISC', value: 'Site Characterization - ISC', enable: false },
          { label: 'Site Characterization – ISI', value: 'Site Characterization – ISI', enable: false },
          { label: 'Site Characterization - LSI', value: 'Site Characterization - LSI', enable: false },
          { label: 'Site Closure', value: 'Site Closure', enable: false },
          { label: 'Site Decision', value: 'Site Decision', enable: false },
          { label: 'Technical Review', value: 'Technical Review', enable: false },
          { label: 'UST Closure', value: 'UST Closure', enable: false },
          { label: 'UST Closure Report', value: 'UST Closure Report', enable: false },
          { label: 'UST Removal Approval', value: 'UST Removal Approval', enable: false },
          { label: 'UST Removal Request', value: 'UST Removal Request', enable: false },
          { label: 'Violation', value: 'Violation', enable: false },
          { label: 'VRP Application', value: 'VRP Application', enable: true }
      ]
    }

  ];
  static stateProgramMappingForScopeOfWork = [
    // {label:'Select State Program', value:null},
    {
      label: 'IN - Brownfields', properties: 
        [
          { label: 'ATG Functionality', value: 'ATG Functionality', enable: false },
          { label: 'Cathodic Protection (Impressed) Test', value: 'Cathodic Protection (Impressed) Test', enable: false },
          { label: 'Cathodic Protection (Sacrificial) Test', value: 'Cathodic Protection (Sacrificial) Test', enable: false },
          { label: 'Compliance Management', value: 'Compliance Management', enable: false },
          { label: 'Drum Disposal', value: 'Drum Disposal', enable: false },
          { label: 'E-Stop and Interstitial Sensor Tests', value: 'E-Stop and Interstitial Sensor Tests', enable: false },
          { label: 'Helium Leak Testing', value: 'Helium Leak Testing', enable: false },
          { label: 'Impact Valve', value: 'Impact Valve', enable: false },
          { label: 'Internal Tank Lining Inspection', value: 'Internal Tank Lining Inspection', enable: false },
          { label: 'Interstitial Tank Pressure Testing', value: 'Interstitial Tank Pressure Testing', enable: false },
          { label: 'Line Tightness Testing', value: 'Line Tightness Testing', enable: false },
          { label: 'Notification Form', value: 'Notification Form', enable: false },
          { label: 'Operator Training', value: 'Operator Training', enable: false },
          { label: 'State Cleanup', value: 'State Cleanup', enable: false },
          { label: 'Sump Sensor', value: 'Sump Sensor', enable: false },
          { label: 'Tank Closure', value: 'Tank Closure', enable: false },
          { label: 'Tank Tightness Testing', value: 'Tank Tightness Testing', enable: false },
          { label: 'Voluntary Remediation Program (VRP)', value: 'Voluntary Remediation Program (VRP)', enable: false },
          { label: 'Active', value: 'Active', enable: false },
          { label: 'Compliant', value: 'Compliant', enable: false },
          { label: 'Deactivated (No Release)', value: 'Deactivated (No Release)', enable: false },
          { label: 'Discontinued (Active)', value: 'Discontinued (Active)', enable: false },
          { label: 'NFA', value: 'NFA', enable: false },
          { label: 'No Paper File (Active)', value: 'No Paper File (Active)', enable: false },
          { label: 'Reffered to Another IDEM Program', value: 'Reffered to Another IDEM Program', enable: false },
        ]
      },
      {
        label: 'IN - ELTF', properties: 
          [
            { label: 'ATG Functionality', value: 'ATG Functionality', enable: false },
            { label: 'Cathodic Protection (Impressed) Test', value: 'Cathodic Protection (Impressed) Test', enable: false },
            { label: 'Cathodic Protection (Sacrificial) Test', value: 'Cathodic Protection (Sacrificial) Test', enable: false },
            { label: 'Compliance Management', value: 'Compliance Management', enable: false },
            { label: 'Drum Disposal', value: 'Drum Disposal', enable: false },
            { label: 'E-Stop and Interstitial Sensor Tests', value: 'E-Stop and Interstitial Sensor Tests', enable: false },
            { label: 'Helium Leak Testing', value: 'Helium Leak Testing', enable: false },
            { label: 'Impact Valve', value: 'Impact Valve', enable: false },
            { label: 'Internal Tank Lining Inspection', value: 'Internal Tank Lining Inspection', enable: false },
            { label: 'Interstitial Tank Pressure Testing', value: 'Interstitial Tank Pressure Testing', enable: false },
            { label: 'Line Tightness Testing', value: 'Line Tightness Testing', enable: false },
            { label: 'Notification Form', value: 'Notification Form', enable: false },
            { label: 'Operator Training', value: 'Operator Training', enable: false },
            { label: 'State Cleanup', value: 'State Cleanup', enable: false },
            { label: 'Sump Sensor', value: 'Sump Sensor', enable: false },
            { label: 'Tank Closure', value: 'Tank Closure', enable: false },
            { label: 'Tank Tightness Testing', value: 'Tank Tightness Testing', enable: false },
            { label: 'Voluntary Remediation Program (VRP)', value: 'Voluntary Remediation Program (VRP)', enable: false },
            { label: 'Active', value: 'Active', enable: false },
            { label: 'Compliant', value: 'Compliant', enable: false },
            { label: 'Deactivated (No Release)', value: 'Deactivated (No Release)', enable: false },
            { label: 'Discontinued (Active)', value: 'Discontinued (Active)', enable: false },
            { label: 'NFA', value: 'NFA', enable: false },
            { label: 'No Paper File (Active)', value: 'No Paper File (Active)', enable: false },
            { label: 'Reffered to Another IDEM Program', value: 'Reffered to Another IDEM Program', enable: false },
          ]
        },
        {
          label: 'IN - LUST', properties: 
            [
              { label: 'ATG Functionality', value: 'ATG Functionality', enable: false },
              { label: 'Cathodic Protection (Impressed) Test', value: 'Cathodic Protection (Impressed) Test', enable: false },
              { label: 'Cathodic Protection (Sacrificial) Test', value: 'Cathodic Protection (Sacrificial) Test', enable: false },
              { label: 'Compliance Management', value: 'Compliance Management', enable: false },
              { label: 'Drum Disposal', value: 'Drum Disposal', enable: false },
              { label: 'E-Stop and Interstitial Sensor Tests', value: 'E-Stop and Interstitial Sensor Tests', enable: false },
              { label: 'Helium Leak Testing', value: 'Helium Leak Testing', enable: false },
              { label: 'Impact Valve', value: 'Impact Valve', enable: false },
              { label: 'Internal Tank Lining Inspection', value: 'Internal Tank Lining Inspection', enable: false },
              { label: 'Interstitial Tank Pressure Testing', value: 'Interstitial Tank Pressure Testing', enable: false },
              { label: 'Line Tightness Testing', value: 'Line Tightness Testing', enable: false },
              { label: 'Notification Form', value: 'Notification Form', enable: false },
              { label: 'Operator Training', value: 'Operator Training', enable: false },
              { label: 'State Cleanup', value: 'State Cleanup', enable: false },
              { label: 'Sump Sensor', value: 'Sump Sensor', enable: false },
              { label: 'Tank Closure', value: 'Tank Closure', enable: false },
              { label: 'Tank Tightness Testing', value: 'Tank Tightness Testing', enable: false },
              { label: 'Voluntary Remediation Program (VRP)', value: 'Voluntary Remediation Program (VRP)', enable: false },
              { label: 'Active', value: 'Active', enable: true },
              { label: 'Compliant', value: 'Compliant', enable: true },
              { label: 'Deactivated (No Release)', value: 'Deactivated (No Release)', enable: true },
              { label: 'Discontinued (Active)', value: 'Discontinued (Active)', enable: true },
              { label: 'NFA', value: 'NFA', enable: true },
              { label: 'No Paper File (Active)', value: 'No Paper File (Active)', enable: true },
              { label: 'Reffered to Another IDEM Program', value: 'Reffered to Another IDEM Program', enable: true },
            ]
          },
          {
            label: 'IN - State Cleanup', properties: 
              [
                { label: 'ATG Functionality', value: 'ATG Functionality', enable: false },
                { label: 'Cathodic Protection (Impressed) Test', value: 'Cathodic Protection (Impressed) Test', enable: false },
                { label: 'Cathodic Protection (Sacrificial) Test', value: 'Cathodic Protection (Sacrificial) Test', enable: false },
                { label: 'Compliance Management', value: 'Compliance Management', enable: false },
                { label: 'Drum Disposal', value: 'Drum Disposal', enable: false },
                { label: 'E-Stop and Interstitial Sensor Tests', value: 'E-Stop and Interstitial Sensor Tests', enable: false },
                { label: 'Helium Leak Testing', value: 'Helium Leak Testing', enable: false },
                { label: 'Impact Valve', value: 'Impact Valve', enable: false },
                { label: 'Internal Tank Lining Inspection', value: 'Internal Tank Lining Inspection', enable: false },
                { label: 'Interstitial Tank Pressure Testing', value: 'Interstitial Tank Pressure Testing', enable: false },
                { label: 'Line Tightness Testing', value: 'Line Tightness Testing', enable: false },
                { label: 'Notification Form', value: 'Notification Form', enable: false },
                { label: 'Operator Training', value: 'Operator Training', enable: false },
                { label: 'State Cleanup', value: 'State Cleanup', enable: false },
                { label: 'Sump Sensor', value: 'Sump Sensor', enable: false },
                { label: 'Tank Closure', value: 'Tank Closure', enable: false },
                { label: 'Tank Tightness Testing', value: 'Tank Tightness Testing', enable: false },
                { label: 'Voluntary Remediation Program (VRP)', value: 'Voluntary Remediation Program (VRP)', enable: false },
                { label: 'Active', value: 'Active', enable: true },
                { label: 'Compliant', value: 'Compliant', enable: true },
                { label: 'Deactivated (No Release)', value: 'Deactivated (No Release)', enable: true },
                { label: 'Discontinued (Active)', value: 'Discontinued (Active)', enable: true },
                { label: 'NFA', value: 'NFA', enable: true },
                { label: 'No Paper File (Active)', value: 'No Paper File (Active)', enable: true },
                { label: 'Reffered to Another IDEM Program', value: 'Reffered to Another IDEM Program', enable: true },
              ]
            },
          {
            label: 'IN - UST', properties: 
              [
                { label: 'ATG Functionality', value: 'ATG Functionality', enable: true },
                { label: 'Cathodic Protection (Impressed) Test', value: 'Cathodic Protection (Impressed) Test', enable: true },
                { label: 'Cathodic Protection (Sacrificial) Test', value: 'Cathodic Protection (Sacrificial) Test', enable: true },
                { label: 'Compliance Management', value: 'Compliance Management', enable: true },
                { label: 'Drum Disposal', value: 'Drum Disposal', enable: true },
                { label: 'E-Stop and Interstitial Sensor Tests', value: 'E-Stop and Interstitial Sensor Tests', enable: true },
                { label: 'Helium Leak Testing', value: 'Helium Leak Testing', enable: true },
                { label: 'Impact Valve', value: 'Impact Valve', enable: true },
                { label: 'Internal Tank Lining Inspection', value: 'Internal Tank Lining Inspection', enable: true },
                { label: 'Interstitial Tank Pressure Testing', value: 'Interstitial Tank Pressure Testing', enable: true },
                { label: 'Line Tightness Testing', value: 'Line Tightness Testing', enable: true },
                { label: 'Notification Form', value: 'Notification Form', enable: true },
                { label: 'Operator Training', value: 'Operator Training', enable: true },
                { label: 'State Cleanup', value: 'State Cleanup', enable: true },
                { label: 'Sump Sensor', value: 'Sump Sensor', enable: true },
                { label: 'Tank Closure', value: 'Tank Closure', enable: true },
                { label: 'Tank Tightness Testing', value: 'Tank Tightness Testing', enable: true },
                { label: 'Voluntary Remediation Program (VRP)', value: 'Voluntary Remediation Program (VRP)', enable: true },
                { label: 'Active', value: 'Active', enable: false },
                { label: 'Compliant', value: 'Compliant', enable: false },
                { label: 'Deactivated (No Release)', value: 'Deactivated (No Release)', enable: false },
                { label: 'Discontinued (Active)', value: 'Discontinued (Active)', enable: false },
                { label: 'NFA', value: 'NFA', enable: false },
                { label: 'No Paper File (Active)', value: 'No Paper File (Active)', enable: false },
                { label: 'Reffered to Another IDEM Program', value: 'Reffered to Another IDEM Program', enable: false },
              ]
            },
            {
              label: 'IN - VRP', properties: 
                [
                  { label: 'ATG Functionality', value: 'ATG Functionality', enable: false },
                  { label: 'Cathodic Protection (Impressed) Test', value: 'Cathodic Protection (Impressed) Test', enable: false },
                  { label: 'Cathodic Protection (Sacrificial) Test', value: 'Cathodic Protection (Sacrificial) Test', enable: false },
                  { label: 'Compliance Management', value: 'Compliance Management', enable: false },
                  { label: 'Drum Disposal', value: 'Drum Disposal', enable: false },
                  { label: 'E-Stop and Interstitial Sensor Tests', value: 'E-Stop and Interstitial Sensor Tests', enable: false },
                  { label: 'Helium Leak Testing', value: 'Helium Leak Testing', enable: false },
                  { label: 'Impact Valve', value: 'Impact Valve', enable: false },
                  { label: 'Internal Tank Lining Inspection', value: 'Internal Tank Lining Inspection', enable: false },
                  { label: 'Interstitial Tank Pressure Testing', value: 'Interstitial Tank Pressure Testing', enable: false },
                  { label: 'Line Tightness Testing', value: 'Line Tightness Testing', enable: false },
                  { label: 'Notification Form', value: 'Notification Form', enable: false },
                  { label: 'Operator Training', value: 'Operator Training', enable: false },
                  { label: 'State Cleanup', value: 'State Cleanup', enable: false },
                  { label: 'Sump Sensor', value: 'Sump Sensor', enable: false },
                  { label: 'Tank Closure', value: 'Tank Closure', enable: false },
                  { label: 'Tank Tightness Testing', value: 'Tank Tightness Testing', enable: false },
                  { label: 'Voluntary Remediation Program (VRP)', value: 'Voluntary Remediation Program (VRP)', enable: false },
                  { label: 'Active', value: 'Active', enable: true },
                  { label: 'Compliant', value: 'Compliant', enable: true },
                  { label: 'Deactivated (No Release)', value: 'Deactivated (No Release)', enable: true },
                  { label: 'Discontinued (Active)', value: 'Discontinued (Active)', enable: true },
                  { label: 'NFA', value: 'NFA', enable: true },
                  { label: 'No Paper File (Active)', value: 'No Paper File (Active)', enable: true },
                  { label: 'Reffered to Another IDEM Program', value: 'Reffered to Another IDEM Program', enable: true },
                ]
              }

    ]




}
